### ISSUE TITLE
GC controller not detected on debian 11/testing

### ISSUE THREAD

**Issue by appzer0** [raphnet/gcn64tools#10]
Hello and thanks for this great piece of hardware I've been using for some years.

Though I cannot get it to work on Debian 11.

udev rules have been copied, udev restarted, 'make' ran OK.

Looking at your udev rules, it seems IDs don't match with kernel-detected IDs.Useful info is in emphasis below:  :

```
root@debian10 src # dmesg -T | tail -n50
[dim. sept. 26 17:40:18 2021] usb 1-7: new low-speed USB device number 11 using xhci_hcd
**[dim. sept. 26 17:40:19 2021] usb 1-7: New USB device found, idVendor=1781, idProduct=0a9a, bcdDevice= 1.02**
[dim. sept. 26 17:40:19 2021] usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[dim. sept. 26 17:40:19 2021] usb 1-7: Product: GC/N64_USB
[dim. sept. 26 17:40:19 2021] usb 1-7: Manufacturer: raphnet.net
**[dim. sept. 26 17:40:19 2021] usb 1-7: SerialNumber: 3782**
[dim. sept. 26 17:40:19 2021] input: raphnet.net GC/N64_USB as /devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-7/1-7:1.0/0003:1781:0A9A.0008/input/input32
[dim. sept. 26 17:40:19 2021] hid-generic 0003:1781:0A9A.0008: input,hidraw0: USB HID v1.01 Gamepad [raphnet.net GC/N64_USB] on usb-0000:03:00.0-7/input0
```

```
root@debian10 src # groups appzer0 
appzer0 : appzer0 cdrom floppy audio dip video **plugdev** netdev bluetooth lpadmin scanner adbusers
```

```
root@debian10 src # lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 0451:0003 Texas Instruments, Inc. SMSL Q5 AMP  
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 046d:c083 Logitech, Inc. G403 Prodigy Gaming Mouse
Bus 001 Device 005: ID 046d:c336 Logitech, Inc. Gaming Keyboard G213
**Bus 001 Device 011: ID 1781:0a9a Multiple Vendors raphnet.net Gamecube/N64 controller**
Bus 001 Device 004: ID 046d:082c Logitech, Inc. HD Webcam C615
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 007: ID 0bda:0151 Realtek Semiconductor Corp. Mass Storage Device (Multicard Reader)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

```
root@debian10 src # ./gcn64ctl -s 3782
Hid enumerate returned NULL
Device not found
```

```
root@debian10 src # ./gcn64ctl -l
Simply listing the devices...
Hid enumerate returned NULL
0 device(s) found
No device found
```

**Comment by raphnet** [comment]
Hello,

Based on the vendor ID (1781) you appear to be using a very old V1 or V2 adapter. The firmware of those adapters is not update-able and has no configurable features. So really, even if the adapter were listed, the tool could do nothing more than listing it.

At some point I can confirm that at least the GUI version of the tool would list those old adapters, but it was only to display that those were not updateable and not configurable. I'm not sure if the command-line tool ever had this feature. Could you confirm if this feature still works in the GUI? (I don't have an old adapter around to test right away, sorry)

Otherwise does the adapter work normally? I.e. Can you see inputs using jstest on /dev/input/js0 ?

**Comment by appzer0** [comment]
Hi and thanks for your reply,

the jstest-gtk and jstest both react perfectly to events from the GC controller.

I bought the adapter a long time ago indeed. I'm going to check is I am able to map events from the controller.
Thanks again.
