### ISSUE TITLE
Linux kernel drivers?

### ISSUE THREAD

**Issue by upintheairsheep** [raphnet/gcn64tools#21]
Could support for the adapters, specifically the firmware of the adapter and the adapters connected to the adapter, the Controller Pak, the Transfer Pak, Multitap memory card, as rewritable storage devices (accessible by /dev)?

**Comment by raphnet** [comment]
Short answer: No, at least not by me. While certainly possible from a purely technical standpoint, but this represents an immense amount of work which I could not possibly complete. And it's a lot easier to update and deploy a simple user space program (as I do now) than a driver.

Could you help me see the big picture here? What is the problem this would solve? What would the benefits exactly? What would become possible that is not already possible with the existing tools?

If the existing user-space tool are not usable or useful for some reason, let's discuss how they could be improved.

In any case, doing this as a linux kernel driver (as the title suggests) would require many iterations, even after a first version works. In order to get this merged into the kernel, there would be a lot of adjusting/redoing to comply with the numerous comments and requests that would undoubtedly arise from the kernel people. But to begin with, given that this is what most people would consider a very niche use case, managing to convince the kernel maintainers to merge such code could also prove difficult. Sure, in that case this could be maintained as an out of tree driver, but this would break from time to time as the kernel evolves, therefore this would be an additional maintenance burden.

Implementing this as a userspace block device would be much more achievable that doing a kernel driver, but this would mean an additional tool or daemon (basically, it would be an additional feature to this project) so while you would be gaining /dev block devices, you would not be getting rid of user-space utilities. So if a userspace tool is required anyway, why not keep things simple and let the tool do the whole job, instead of insisting on presenting thins as a /dev/ block devices?
